language: cpp

sudo: required

services:
    - docker

os:
    - linux

matrix:
    include:
        - name: "RaZ - GCC"
          env:
            - CXX=g++
            - CC=gcc
            - RUN_TESTS=false

        - name: "RaZ - Clang"
          env:
            - CXX=clang++
            - CC=clang
            - RUN_TESTS=false

        - name: "RaZ - GCC + Tests"
          env:
            - CXX=g++
            - CC=gcc
            - RUN_TESTS=true

        - name: "RaZ - Clang + Tests"
          env:
            - CXX=clang++
            - CC=clang
            - RUN_TESTS=true

# Disabling depth to fetch only the latest commit
git:
    depth: false

install:
    - docker build -t raz .

script:
    # Run Docker, build RaZ & launch unit tests
    - docker run --name RaZ -v `pwd`:/RaZ raz
        bash -c "
            mkdir build &&
            cd build/ &&
            cmake -G \"Unix Makefiles\" -DRAZ_BUILD_EXAMPLES=true -DRAZ_RUN_TESTS=${RUN_TESTS} -DRAZ_USE_FBX=true .. &&
            make -j4 ;
            if [[ ${RUN_TESTS} == true ]]; then ./tests/RaZ_Tests; fi
        "

#webhooks:
#    urls:
#        secure: URL
#    on_success: change
#    on_failure: always
#    on_start: never
#    on_cancel: never
#    on_error: always
