language: cpp

sudo: required

compiler:
    - gcc
    - clang

services:
    - docker

os:
    - linux

# Disabling depth to fetch only the latest commit
git:
    depth: false

install:
    - docker build -t raz .

script:
    # Run Docker, build RaZ & launch unit tests
    - docker run --name RaZ -v `pwd`:/RaZ raz
        sh -c "
            mkdir build &&
            cd build/ &&
            cmake -G \"Unix Makefiles\" -DRAZ_BUILD_EXAMPLES=true -DRAZ_RUN_TESTS=true -DRAZ_USE_FBX=true -DRAZ_GEN_DOC=false .. &&
            make -j4 ;
            ./tests/RaZ_Tests
        "

#webhooks:
#    urls:
#        secure: URL
#    on_success: change
#    on_failure: always
#    on_start: never
#    on_cancel: never
#    on_error: always
