language: cpp

sudo: required

services:
    - docker

os:
    - linux

matrix:
    include:
        - name: "RaZ - GCC"
          env:
            - CXX_COMPILER=g++
            - C_COMPILER=gcc
            - RUN_TESTS=false

        - name: "RaZ - Clang"
          env:
            - CXX_COMPILER=clang++
            - C_COMPILER=clang
            - RUN_TESTS=false

        - name: "RaZ - GCC + Tests"
          env:
            - CXX_COMPILER=g++
            - C_COMPILER=gcc
            - RUN_TESTS=true

        - name: "RaZ - Clang + Tests"
          env:
            - CXX_COMPILER=clang++
            - C_COMPILER=clang
            - RUN_TESTS=true

# Disabling depth to fetch only the latest commit
git:
    depth: false

install:
    - docker build -t raz .

script:
    # Run Docker, build RaZ & launch unit tests
    - docker run --name RaZ -w /RaZ -v `pwd`:/RaZ raz
        bash -c "
            cmake -G \"Unix Makefiles\" -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DCMAKE_C_COMPILER=${C_COMPILER} \
                                        -DRAZ_BUILD_EXAMPLES=true -DRAZ_RUN_TESTS=${RUN_TESTS} -DRAZ_USE_FBX=true . &&
            make -j4 &&
            if [[ ${RUN_TESTS} == true ]]; then ./tests/RaZ_Tests; fi
        "

#webhooks:
#    urls:
#        secure: URL
#    on_success: change
#    on_failure: always
#    on_start: never
#    on_cancel: never
#    on_error: always
